flux_path: "black-forest-labs/FLUX.1-dev"
dtype: "bfloat16"

model:
  independent_condition: false

train:
  accumulate_grad_batches: 8
  dataloader_workers: 16
  log_freq: 1000
  save_interval: 1000
  sample_interval: 1000
  max_epochs: 100 # Just to avoid setting max_epocohs to -1 that activates infinite training
  max_steps: 200000
  gradient_checkpointing: true # (Turn off for faster training)
  save_path: "runs"
  exp_name: "omini_pose_x1"
  exp_version: "v0"

  # Specify the type of condition to use. 
  # Options: ["canny", "coloring", "deblurring", "depth", "depth_pred", "fill"]
  condition_type: "pose"
  dataset:
    target: omini.pipeline.datasets.PoseControl
    params:
      root: <path_to_parent_directory>/ControlNet/control_datasets/coco_keypoints/train
      metadata_path: <path_to_parent_directory>/ControlNet/control_datasets/coco_keypoints/train/metadata.csv
      keypoints_json_path: <path_to_parent_directory>/ControlNet/person_keypoints_train2017.json
      condition_size: 
        - 512
        - 512
      target_size: 
        - 512
        - 512
      p_drop: 0.5

  wandb:
    project: "OminiControl"

  lora_config:
    r: 4
    lora_alpha: 4
    init_lora_weights: "gaussian"
    target_modules: "(.*x_embedder|.*(?<!single_)transformer_blocks\\.[0-9]+\\.norm1\\.linear|.*(?<!single_)transformer_blocks\\.[0-9]+\\.attn\\.to_k|.*(?<!single_)transformer_blocks\\.[0-9]+\\.attn\\.to_q|.*(?<!single_)transformer_blocks\\.[0-9]+\\.attn\\.to_v|.*(?<!single_)transformer_blocks\\.[0-9]+\\.attn\\.to_out\\.0|.*(?<!single_)transformer_blocks\\.[0-9]+\\.ff\\.net\\.2|.*single_transformer_blocks\\.[0-9]+\\.norm\\.linear|.*single_transformer_blocks\\.[0-9]+\\.proj_mlp|.*single_transformer_blocks\\.[0-9]+\\.proj_out|.*single_transformer_blocks\\.[0-9]+\\.attn.to_k|.*single_transformer_blocks\\.[0-9]+\\.attn.to_q|.*single_transformer_blocks\\.[0-9]+\\.attn.to_v|.*single_transformer_blocks\\.[0-9]+\\.attn.to_out)"
    # (Uncomment the following lines to train less parameters while keeping the similar performance)
    # target_modules: "(.*(?<!single_)transformer_blocks\\.[0-9]+\\.norm1\\.linear|.*(?<!single_)transformer_blocks\\.[0-9]+\\.attn\\.to_k|.*(?<!single_)transformer_blocks\\.[0-9]+\\.attn\\.to_q|.*single_transformer_blocks\\.[0-9]+\\.norm\\.linear|.*single_transformer_blocks\\.[0-9]+\\.attn.to_k|.*single_transformer_blocks\\.[0-9]+\\.attn.to_q)"

  optimizer:
    type: "Prodigy"
    params:
      lr: 1
      use_bias_correction: true
      safeguard_warmup: true
      weight_decay: 0.01

  # (To use AdamW Optimizer, uncomment the following lines)
  # optimizer:
  #   type: AdamW
  #   lr: 1e-4
  #   weight_decay: 0.001
eval:
  eval_callback_type: detection
  eval_freq: 1000
  eval_batch_size: 4
  eval_num_workers: 8
  eval_cfg_scale: 7.5
  num_eval_images: 64
  dataset:
    target: omini.pipeline.datasets.PoseControl
    params:
      root: <path_to_parent_directory>/ControlNet/control_datasets/coco_keypoints/val
      metadata_path: <path_to_parent_directory>/ControlNet/control_datasets/coco_keypoints/val/metadata.csv
      keypoints_json_path: <path_to_parent_directory>/ControlNet/person_keypoints_val2017.json
      condition_size: 
        - 512
        - 512
      target_size: 
        - 512
        - 512
      p_drop: 0.

  evaluator:
    target: omini.pipeline.control_evaluators.PoseEvaluator